# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: 273do
# "service" is the name of this project. This will also be added to your AWS resource names.
service: express-with-aws-lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1

functions:
  api:
    handler: handler.handler
    events:
      - http:
          method: ANY
          path: "/"
          cors: true
      - http:
          method: ANY
          path: "/{any+}"
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
